-- MySQL Script generated by MySQL Workbench
-- Mon Apr 15 11:03:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`estilista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estilista` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estilista` (
  `idEstilista` INT NOT NULL,
  `dni` VARCHAR(9) NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstilista`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`galeria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`galeria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`galeria` (
  `idgaleria` INT NOT NULL,
  `descripcion` VARCHAR(60) NULL,
  `estilista_id` INT NOT NULL,
  PRIMARY KEY (`idgaleria`, `estilista_id`),
  INDEX `fk_galeria_estilista_idx` (`estilista_id` ASC) VISIBLE,
  CONSTRAINT `fk_galeria_estilista`
    FOREIGN KEY (`estilista_id`)
    REFERENCES `mydb`.`estilista` (`idEstilista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idCliente` INT NOT NULL,
  `dni` VARCHAR(9) NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tratamientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tratamientos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tratamientos` (
  `idTratamientos` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `duracion` INT NULL,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`idTratamientos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`citas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`citas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`citas` (
  `idhorario` INT NOT NULL,
  `fecha` DATE NULL,
  `hora` VARCHAR(45) NULL,
  `Tratamientos_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `estilista_id` INT NOT NULL,
  PRIMARY KEY (`idhorario`, `Tratamientos_id`, `cliente_id`, `estilista_id`),
  INDEX `fk_horario_Tratamientos1_idx` (`Tratamientos_id` ASC) VISIBLE,
  INDEX `fk_horario_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_horario_estilista1_idx` (`estilista_id` ASC) VISIBLE,
  CONSTRAINT `fk_horario_Tratamientos1`
    FOREIGN KEY (`Tratamientos_id`)
    REFERENCES `mydb`.`Tratamientos` (`idTratamientos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horario_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horario_estilista1`
    FOREIGN KEY (`estilista_id`)
    REFERENCES `mydb`.`estilista` (`idEstilista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
